language: java
sudo: false
jdk:
  - oraclejdk8
cache:  
  directories:  
   - $HOME/.m2  

notifications:
  email:
    recipients:
      - vitruv-build@ira.uni-karlsruhe.de
      
before_install:
    - git clone --depth 1 https://github.com/kit-sdq/BuildUtilities.git /tmp/BuildUtilities
    - . /tmp/BuildUtilities/travis-ci/installMaven.sh
install: true

script: mvn clean verify

after_success:
- . /tmp/BuildUtilities/travis-ci/deploy.sh license releng/tools.vitruv.updatesite repository vitruv-tools updatesite